############################### 基本信息 ###############################
info:
  cdn: # 把对应的那一行注释掉就使用本地的文件
    css:
      style: http://dl0.arlxn.xyz/CDN/blog/1/style.css
    js:
      app: http://dl0.arlxn.xyz/CDN/blog/1/app.js
      search: http://dl0.arlxn.xyz/CDN/blog/1/search.js
      volantis: http://dl0.arlxn.xyz/CDN/blog/2/volantis.min.js

############################### 主题风格 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure          # pure: 导航栏和标题栏背景是白色

############################### 服务开关 ###############################
scrollreveal: true
nodewaves: true

############################### 默认值 ###############################
# 音乐控件的默认配置，如果sidebar或者page里没有提供，就取这里的参数
music:
  enable: true      # 是否启用
  color: '#1BCDFC'  # 主题色
  mode: single      # random （随机） single （单曲） circulation （列表循环） order （列表）
  server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
  type: song        # song （单曲） album （专辑） playlist （歌单） search （搜索）
  id: 493911        # 歌曲/专辑/歌单 ID
  volume: 0.3       # 音量, 0~1
  autoplay: false   # 自动播放

# 友链页头像占位图
avatar_placeholder: http://dl0.arlxn.xyz/CDN/Logo.png

# 日期格式 http://momentjs.com/docs/
date_format: 'YYYY-MM-DD' # 文章发布日期的格式
updated_date_format: 'll' # 文章更新日期的格式

# 幻灯片
backstretch:
  position: full  # cover: 封面背景   full: 整个网页背景
  duration: 3000  # 持续时间（毫秒）
  fade: 1700      # 渐变（毫秒）
  images:
    - http://dl0.arlxn.xyz/CDN/bgp190930.png

############################### 自定义 ###############################
# page的封面
cover:
  scheme: search    # 后期将会提供多种封面方案
  height: half      # full（默认值）: 首页封面占据整个第一屏幕，其他页面占半个屏幕高度， half: 所有页面都封面都只占半个屏幕高度
  title: "ArLxn"
  # logo: assets/logo.png    # logo和title只显示一个，若同时设置，则只显示logo
  search_placeholder: '探索异次元的世界'
  # 主页封面菜单
  features:
    - name: 主站
      icon: fas fa-rss
      url: /
    # - name: 项目
      # icon: fas fa-code-branch
      # url: https://github.com/arlxn
    - name: 工作室
      icon: fas fa-archive
      url: https://trfgs.arlxn.xyz
      rel: nofollow
    - name: 图库
      icon: fas fa-images
      url: Gallery/index.html
      rel: nofollow
    - name: 友人帐
      icon: fas fa-link
      url: friends/
      rel: nofollow
    - name: 关于
      icon: fas fa-info-circle
      url: about/
      rel: nofollow

# 桌面端导航栏菜单
menu_desktop:
  - name: 主站
    icon: far fa-file-code
    url: /
  - name: 图库
    icon: fas fa-images
    url: /gallery/gallery.html
    rel: nofollow
  - name: 工作室
    icon: fas fa-archive
    url: https://trfgs.arlxn.xyz
    rel: nofollow
  - name: Git
    icon: fab fa-github-square
    url: git/
  - name: 友人帐
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: 材料下载
    icon: fa fa-cloud-download
    url: paperdl/
    rel: nofollow
  - name: 关于
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# 手机端导航菜单（从右上角的按钮点击展开）
menu_mobile:
  - name: 主页
    icon: fas fa-clock
    url: /
  - name: 友人帐
    icon: fas fa-link
    url: friends/
    rel: nofollow
  - name: 反馈
    icon: fa fa-comments
    url: feedback/
  - name: 材料下载
    icon: fa fa-cloud-download
    url: paperdl/
    rel: nofollow
  - name: 关于
    icon: fas fa-info-circle
    url: about/
    rel: nofollow

# 默认的meta信息，文章中没有配置则按照这里的配置来显示，设置为false则不显示
# 其中，title只在header中有效，music和thumbnail无需在这里设置，文章中有则显示
# 如果tags放置在meta.header中，那么在post列表中不显示（因为卡片下方已经有了）
meta:
  header: [title, author, date, categories, counter, top]
  footer: [updated, tags, share]

# 主体元素，你也可以在页面的Front-matter中设置
body: [article, comments]

# 侧边栏小部件，默认按下面给定的顺序全部显示，文章中还可以自定义显示一部分以及顺序
sidebar:
  - widget: author
    avatar: http://dl0.arlxn.xyz/CDN/Logo.png
    title: Lxn's Area
    body: 大切な人と再会できる日を
    social: true
  - widget: toc
  - widget: plainsd
  - widget: grid
    icon: fas fa-map-signs
    title: 看这里，不迷路
    rows:
      - name: 主页
        icon: fas fa-clock
        url: /
      - name: 番剧列表
        icon: far fa-file-video
        url: bangumi/
        rel: nofollow
      - name: Git
        icon: fab fa-github-square
        url: git/
      - name: 友人帐
        icon: fas fa-link
        url: friends/
        rel: nofollow
      - name: 反馈
        icon: fa fa-comments
        url: feedback/
      - name: 材料下载
        icon: fa fa-cloud-download
        url: paperdl/
        rel: nofollow
      - name: 关于小站
        icon: fas fa-info-circle
        url: about/
        rel: nofollow
  # - widget: plain
    # icon: fa fa-location-arrow
    # title: 让我看看你在哪
    # body: '![](https://ip.ntrqq.net/images/kiminona.png?wd=JUU2JUFDJUEyJUU4JUJGJThFJUU2JTlEJUE1JUU1JTg4JUIwJUU2JTg4JTkxJUU3JTlBJTg0JUU1JUJDJTgyJUU2JUFDJUExJUU1JTg1JTgzJUU3JUE5JUJBJUU5JTk3JUI0JUVGJUJDJTgx&r=52uzpn80juf)'
  # - widget: category
    # more:
      # icon: fas fa-expand-arrows-alt
      # url: blog/categories/
      # rel: nofollow
  - widget: music
    icon: fas fa-compact-disc
    title: "background Music"
    more:
      icon: far fa-heart
      url: https://music.163.com/#/playlist?id=823256880
      rel: external nofollow noopener noreferrer
      target: _blank
    server: netease   # netease（网易云音乐）tencent（QQ音乐） xiami（虾米） kugou（酷狗）
    type: song        # song （单曲） album （专辑） playlist （歌单） search （搜索）
    id: 493911        # 歌曲/专辑/歌单 ID

# 社交信息
social:
  - icon: fab fa-qq
    url: http://wpa.qq.com/msgrd?v=3&uin=1762165046&site=qq&menu=yes
  - icon: fas fa-envelope
    url: mailto:LingXuanNing@Outlook.com
  - icon: fab fa-telegram-plane
    url: https://t.me/arlxn
  - icon: fas fa-headphones-alt
    url: https://music.163.com/#/playlist?id=823256880

# 分享按钮
# 当id为qrcode时需要安装插件  npm i -S hexo-helper-qrcode
share:
  - id: qq
    name: QQ好友
    img: http://dl0.arlxn.xyz/CDN/blog/1/qq.png
  - id: qzone
    name: QQ空间
    img: http://dl0.arlxn.xyz/CDN/blog/1/qzone.png
  # - id: qrcode
  #   name: 微信
  #   img: http://dl0.arlxn.xyz/CDN/blog/1/wechat.png
  - id: weibo
    name: 微博
    img: http://dl0.arlxn.xyz/CDN/blog/1/weibo.png
  # - id: qrcode
  #   name: QRcode
  #   img: http://dl0.arlxn.xyz/CDN/blog/1/qrcode.png

# 这个现在已经无效了，在footer.ejs里面改
footer: '--------------------我是有底线的--------------------'

############################### 评论系统 ###############################
# disqus_shortname: 要使用哪个请复制到根目录配置文件！
# livere_uid: 要使用哪个请复制到根目录配置文件！
# gitalk: 要使用哪个请复制到根目录配置文件！
#   clientID: 你的clientID
#   clientSecret: 你的clientSecret
#   repo: 你的repo名
#   owner: 你的GitHub名
#   admin: [] 至少填写你的GitHub名
# leancloud: 要使用哪个请复制到根目录配置文件！
#   app_id: 你的appId
#   app_key: 你的appKey

############################### 杂项，请勿删除 ###############################
#valine配置
valine:
  enable: true # 如果你想用Valine评论系统，请设置enable为true
  volantis: true # 是否启用volantis版本（禁止匿名，增加若干贴吧、QQ表情）
  # 还需要在根目录配置文件中添加下面这三行内容
  # leancloud:
  #   app_id: 你的appId
  #   app_key: 你的appKey
  guest_info: nick,mail #valine comment header info
  placeholder: 请填写正确的邮箱以收到回复（建议使用QQ邮箱：格式为：QQ号+@qq.com。例如：1762165046@qq.com）。 # valine comment input placeholder(like: Please leave your footprints )
  avatar: mp            # gravatar style https://valine.js.org/avatar
  pageSize: 10          # comment list page size
  verify: true          # valine verify code (true/false)
  notify: true          # valine mail notify (true/false)
  lang: zh-cn
  highlight: true

# 搜索配置
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less渲染
less:
  compress: true
