# CDN for mathjax
location:

# style
style:
  scheme: 'plus'
  bg_img: /img/bg.png
  avatar: /img/Lxn.png
  slogan: "洁白、闪耀、奇迹、之花，White Lily！"
  hoverable: true

# HTML head
head:
  favicon: https://img.vim-cn.com/7d/7e77325c2cca244d795b0b2427ac27f3467233.png
  high_res_favicon: /img/gkgray.png
  apple_touch_icon: /img/gkgray.png
  keywords: blog, lxn, arlxn, github

# color
color:
  primary_color: "pink"
  accent_color: "deep-orange"
  layout:
  random:
  bg_color: "#eeeeee"

# appbar
appbar:
  title: "ArLxn"
  search: true

index:
  welcome: "绽放！就算只有刹那光芒。"
  notification: true

# post settings
post:
  entry_excerpt: 32
  qr_code: true
  prism:
    theme:
    line_number: true
  license:
    name: 'MIT License'
    link:  '/'
  word_count: true
  read_time: true
  toc_list_number: true
  donate:
    微信:
      link: /img/WechatPayPic.png
      fa: 'fa-wechat'
    QQ:
      link: /img/QQPayPic.png
      fa: 'fa-qq'


share_menu:
#  rss: false
 weibo: true
 twitter: true
 facebook: true
 # googleplus: true
 # linkedin: true
 qq: true
 telegram: true

# use:disqus, valine or custom
comment:
    use: valine
    shortname: arlxn
    # https://valine.js.org
    valine:
      appid: FaPviMpokcX2ndnQdHytN1v8-gzGzoHsz
      appkey: UlWdvASdXH3DRdJtxYuTfS2E
      notify: true 
      verify: true 
      avatar: mp
      placeholder: 不说点什么嘛？（请不要发布违反当地法律、诋毁政府及所有不应出现的内容）
      guest_info: nick,mail # reviewer attributes:",link"
      recordIP: true

# pagination
# github@zllovesuki
pagination: 2

# footer
footer:
  since: 2019
  ICP: 陌上花开花不败
  image: /img/bg.png
  last_updated: true

# Plugins
busuanzi:
#  all_site_uv: true
#  post_pv: true
#  busuanzi_pure_mini_js: "//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

service_woker:

about_me: true

pace: false

random_pics: 44

pages:
  在QQ上和我对话:
    link: http://wpa.qq.com/msgrd?v=3&uin=1762165046&site=qq&menu=yes
    fa: "fa-qq"
  给我发邮件:
    link: "mailto:LingXuanNing@Outlook.com"
    fa: "fa-envelope-open-text"
#  Test1:
#    link: "/myfriends"
#    md: "&#xe0ba;"
# 关于这个小站:
   # link: "/admin/about.html"
   # fa: "fa-info-circle"
#  Test3:
#    link: "/timeline"
#    md: "home"
# 联系我:
   # cascade: true
   # fa: "fa-mobile-android"
   # pages:

sns:
  QQ:
    link: "http://wpa.qq.com/msgrd?v=3&uin=1762165046&site=qq&menu=yes"
    fa: "fa-qq"
  Email:
    link: "mailto:LingXuanNing@Outlook.com"
    fa: "fa-envelope-open-text"
#  Twitter:
#    link: https://twitter.com
#    fa: 'fa-twitter'
#  Facebook:
#    link: https://facebook.com
#    null_icon: true


# Vendors
vendors:
  fonts_min_css:
  style_min_css:
  js_min_js:
  outdatedbrowser_min_js:
  pace_min_js:
  pace_style_css:
  custom_head:
  custom_js:
