theme_color:
  primary: pink
  accent: blue

notice:

favicon: /images/favicon.png
banner: /images/banner.png
avatar: /images/avatar.png
rss: /atom.xml

email: LingXuanNing@Outlook.com
sns:
  twitter:
  facebook:
  google_plus:
  weibo: https://weibo.com/XuanNingSakura
  instagram:
  tumblr:
  github: https://github.com/ArLxn
  linkedin:
  zhihu: 
  douban:
  qq: tencent://message/?uin=1762165046&Menu=yes
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google: 
  baidu: 
analytics:
  google_site_id: 
  baidu_site_id: 
  cnzz_site_id:

pages:
- name: 标签云
  link: /tagcloud
- name: 画廊
  link: /gallery
links:
- name: 我的简历
  link: http://images.niemingzhao.top/my_resume.html

since: 2018
footer_text: " | LingXuanNing"
license: 本文遵循 <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">CC BY-NC-SA 4.0</a> 许可协议

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
donate:
- name: 支付宝
  link: /images/alipay.jpg
- name: 微信支付
  link: /images/wechat.jpg
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin
comment:
  use: changyan
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  changyan_app_id: 
  changyan_app_key: 
  changyan_sid_type: 
