# Header Menu
menu:
  主页: /
  目录: /archives
  材料下载: /admin/1701-Studio.html
  Github: https://github.com/ArLxn
  关于本站: /admin/about.html
rss: /atom.xml

# Set to false to disable banner
use_header_cover: true

# URL of the banner image
# Put your custom banner image under
# the theme's img folder: your-blog/themes/minimal-dual/source/img/
# and modify index_cover's value like so:
# index_cover: /img/your-custom-banner.jpg
# or
# Put your custom banner image under
# your blog's images folder: your-blog/source/images/
# and modify index_cover's value like so:
# index_cover: /images/your-custom-banner.jpg
# or
# Specify an online resource like so:
# index_cover: http://somewhere.com/path/to/banner.jpg
index_cover: /img/ArLxn.jpg

widgets:
- category
- tag
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# favicon
favicon: /img/favicon.png

# Google Analytics Tracking ID
google_analytics:

