# Theme config
router: true

style:
  primary_color: "pink"
  accent_color: "pink"
  bg_color: "#eeeeee"
  hoverable: true

info:
  bg_image: /images/bg.png
  avatar: /images/Lxn.png
  slogan: "一起逃离太阳系"
  # sns:
    # QQ:
      # link: http://wpa.qq.com/msgrd?v=3&uin=1762165046&site=qq&menu=yes
      # fa: 'fa-qq'


# HTML head
head:
  favicon: /images/Lxn.png
  high_res_favicon: /images/Lxn.png
  apple_touch_icon: /images/Lxn.png
  keywords: blog, ArLxn, Lxn, lxn, arlxn, technology

# Search
search: true

# Post
post:
  entry_excerpt: 80
  random_pics: 44
  qr_code: true
  prism:
    theme: darcula
    line_number: true
  license:
    name: 'Licenses For ArLxn v1.19'
    link:  'https://ArLxn.github.io/admin/Licenses.html'
  word_count: false
  read_time: true
  donate:
    # wechat:
      # link: /img/avatar.png
      # fa: 'fa-wechat'
    # paypay:
      # link: 'https://paypal.com'
      # fa: 'fa-paypal'

share_menu:
  rss: false
  weibo: false
  twitter: true
  facebook: true
  googleplus: true
  linkedin: true
  qq: true
  telegram: true

pages:
  # Test1:
    # link: "/friends"
    # type: 'internal'
    # md: "&#xe0ba;"
  # Test2:
    # link: "/apply-for-link"
    # type: 'internal'
    # fa: "fa-child"
  # Test3:
    # link: "/galleries"
    # type: 'internal'
    # md: "home"
  # Test4:
    # cascade: true
    # md: 'home'
    # pages:
      # TEST1:
        # link: "/myfriends"
        # type: 'internal'
        # md: "&#xe5ca;"
      # TEST2:
        # link: "/timeline"
        # type: 'internal'
        # md: "home"

# comment
comment:
    use:
    shortname:

# footer
footer:
  since: 2019
  ICP:
  image:
  last_updated:

# Service Worker
service_worker:

# scss
node_sass:
  debug: false
  outputStyle: compressed
  precision: 5
  sourceComments: false

# Vendors
vendors:
  style_min_css:
  outdatedbrowser_min_js:
  js_min_js:
  custom_head:
  custom_js:

debug: false